apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ex01
  namespace: default
  labels:
    app: frontend-ex01
spec:
  selector:
    matchLabels:
      app: frontend-ex01
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend-ex01
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  frontend-exercise-01
        image:  nhanphanminh/k8s-best-practice-chap01:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
      restartPolicy: Always